from pydantic import BaseModel, Field
from typing import Literal, Optional, List, Union

# --- Input Models ---
class UserRequest(BaseModel):
    """
    Represents the incoming request from the Discord bot.
    """
    user_id: int = Field(..., description="Discord User ID of the requester")
    guild_id: int = Field(..., description="Discord Guild ID where the command was issued")
    content: str = Field(..., description="Natural language request content")

# --- Action Models (Agent Output) ---

class BaseAction(BaseModel):
    """
    Base model for all actions the agent can propose.
    """
    action_type: str = Field(..., description="The type of action to perform")
    reasoning: str = Field(..., description="Why this action is being taken")

class CreateRoleAction(BaseAction):
    action_type: Literal["create_role"] = "create_role"
    name: str = Field(..., description="Name of the role to create")
    color: Optional[int] = Field(None, description="Color of the role (integer)")
    permissions: Optional[int] = Field(None, description="Bitwise permissions integer")
    hoist: bool = Field(False, description="Whether to display the role separately")
    mentionable: bool = Field(False, description="Whether the role is mentionable")

class CreateChannelAction(BaseAction):
    action_type: Literal["create_channel"] = "create_channel"
    name: str = Field(..., description="Name of the channel to create")
    type: Literal["text", "voice", "category"] = Field("text", description="Type of channel")
    topic: Optional[str] = Field(None, description="Channel topic")
    category: Optional[str] = Field(None, description="Name of the category to place this channel in")

class DeleteRoleAction(BaseAction):
    action_type: Literal["delete_role"] = "delete_role"
    name: str = Field(..., description="Name of the role to delete")

class DeleteChannelAction(BaseAction):
    action_type: Literal["delete_channel"] = "delete_channel"
    name: str = Field(..., description="Name of the channel to delete")
    
class CreateInviteAction(BaseAction):
    action_type: Literal["create_invite"] = "create_invite"
    channel_name: str = Field(..., description="Name of the channel to create invite for")
    max_uses: int = Field(0, description="Max uses for the invite (0 for infinite)")
    expires_in_minutes: int = Field(1440, description="Expiration time in minutes (default 24h)")

class ModerationAction(BaseAction):
    action_type: Literal["kick_user", "ban_user", "unban_user", "mute_user", "unmute_user"]
    user_id: int = Field(..., description="Target User ID")
    reason: Optional[str] = Field(None, description="Reason for moderation action")

# Union of all possible actions
Action = Union[
    CreateRoleAction,
    CreateChannelAction,
    DeleteRoleAction,
    DeleteChannelAction,
    CreateInviteAction,
    ModerationAction
]

class ExecutionPlan(BaseModel):
    """
    The structured plan generated by the agent.
    """
    thought_process: str = Field(..., description="Chain of thought reasoning")
    actions: List[Action] = Field(..., description="List of actions to execute")
    final_response: str = Field(..., description="Response to send back to the user")
